- shell:
    - [/bin/sh etc/init/base.sh]
    - [rm -f ~/.xprofile]
    - [rm -f ~/.Xresources]
    - [rm -f ~/.i3/config]
    - [rm -rf ~/.config/i3blocks]
    - [rm -rf ~/.config/nitrogen]
    - [rm -rf ~/.config/fcitx]

- link:
    ~/.xprofile: home/.xprofile
    ~/.Xresources: home/.Xresources
    ~/.i3/config: home/.i3/config
    ~/.config/i3blocks: home/.config/i3blocks
    ~/.config/fcitx/config: home/.config/fcitx/config
    ~/.config/fcitx/profile: home/.config/fcitx/profile
    ~/.config/fcitx/addon: home/.config/fcitx/addon
    ~/.config/fcitx/conf: home/.config/fcitx/conf
    ~/.config/nitrogen: home/.config/nitrogen
