- shell:
  - [/bin/sh etc/init/base.sh]

- link:
  ~/.xprofile: home/.xprofile
  ~/.Xresources: home/.Xresources
  ~/.config/fcitx/config: home/.config/fcitx/config
  ~/.config/fcitx/profile: home/.config/fcitx/profile
  ~/.config/fcitx/addon: home/.config/fcitx/addon
  ~/.config/fcitx/conf: home/.config/fcitx/conf
