swipe:
  3:
    left:
      command: 'xdotool key alt+Left'
    right:
      command: 'xdotool key alt+Right'
    up:
      command: 'xdotool key ctrl+t'
    down:
      command: 'xdotool key ctrl+w'
  4:
    left:
      command: 'xdotool key control+super+Left'
    right:
      command: 'xdotool key control+super+Right'
    up:
      command: 'skippy-xd'
    down:
      command: 'xdotool key control+shift+t'
pinch:
  2:
    in:
      command: 'xdotool key ctrl+plus'
    out:
      command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.5
  pinch: 0.1

interval:
  swipe: 1
  pinch: 1
